name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS and Deploy Project
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Start the SSH agent and add the private key
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/github

            # Clone the repository
            cd /var/www/personal-site || git clone git@github.com:nmmanas/personal-site.git /var/www/personal-site
            cd /var/www/personal-site

            # Pull the latest changes from the repository
            git pull origin main

            # run deployment script from file
            ./deploy.sh